FWD: 'CCTACGGGNGGCWGCAG'
REV: 'GACTACHVGGGTATCTAATCC'

CUT_COUNT_PERCENT: 0.9
CUT_QUALITY_PERCENT: 25
CUT_QUALITY_LOCATION: 50

TAXONOMY_DATABASE: './silva-138-99-nb-classifier.qza'

CUTADAPT_CORES: 4
DADA2_CORES: 4
TAXONOMY_CORES: 4
